### ISSUE TITLE
update lodash?

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#2991]
i am getting the following warning during build:

```
:dev:core:npmInstallnpm WARN deprecated lodash@2.4.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^3.0.0.
```

**Comment by scottdraves** [comment]
2.4.2 is from dec 2013 so rather old.  lodash is working on 4.0 even.
but there are some incompatible changes going from 2 to 3, and just dropping it in results in an error:
Uncaught TypeError: _.range is not a function
but i think that's because it did not load at all.

@ildipo what do you think about upgrading beaker lab?

**Comment by tomca32** [comment]
yeah _.range is definitely a function in the latest lodash so I don't think it's a compatibility issue. I'll look into this.

**Comment by scottdraves** [comment]
davide approves

**Comment by tomca32** [comment]
Unfortunately we are using lodash.underscore - a build of lodash wit extra underscore compatibilities. That build doesn't exist in versions 3.x.x of lodash.

Using regular lodash causes weird bugs in beaker. I guess we are using the underscore API somewhere. Lodash and Underscore are very similar so this is probably a small change. I just need to find where.

**Comment by tomca32** [comment]
The compatibility problem is that lodash is using lazy evaluation with its chaining syntax. For some reason we are using the chaining syntax in a lot of places where its unnecessary, for example:

```
_(collection).each(function(e){e.doSomething()});
```

Now this won't evaluate until the chaining result is requested with a call to .value() - since we don't care about the result we don't call value.
All occurrences of this syntax should be replaced with:

```
_.each(collection, function(e) {e.doSomething();});
```

In cases where we are actually using chaining we should call to value at the end:

```
_(collection).doSomething().doSomethingElse().value();
```

https://lodash.com/docs#_
