### ISSUE TITLE
Error in browser console when open R tutorial

### ISSUE THREAD

**Issue by mnavasiolava** [twosigma/beakerx#3069]
after update from master get this error

```
TypeError: bkNotebookWidget.getFocusable(...).scrollTo is not a function
    at go (beakerApp.js:4281)
    at Object._impl.go2FirstErrorCodeCell (beakerApp.js:4293)
    at Object.bkHelper.go2FirstErrorCodeCell (beakerApp.js:2718)
    at :8801/8fdd768/beaker/plugin/menu/notebook.js:57
```

**Comment by tomca32** [comment]
Confirmed. But I only get it when I run all cells after opening.

This seems like it was caused by https://github.com/twosigma/beaker-notebook/pull/3047 - @kpaharelau can you take a look?

**Comment by tomca32** [comment]
This is the line: https://github.com/twosigma/beaker-notebook/blob/492429eef95a040db134ae9cfa7b251ff294b46b/core/src/main/web/app/mainapp/mainapp.js#L794

**Comment by scottdraves** [comment]
i'm not seeing this.

**Comment by mnavasiolava** [comment]
Tomislav was right, you should also run all cells to see the error

**Comment by scottdraves** [comment]
i did!

**Comment by mnavasiolava** [comment]
and still nothing?

**Comment by tomca32** [comment]
try the groovy one. It happens when the cell errors for any reason

**Comment by scottdraves** [comment]
OK I get it from the groovy error.
we do want to scroll to show an error when they happen.
we just have to use a method that exists...
