### ISSUE TITLE
Current Scala version (2.12) is not compatible with current Spark

### ISSUE THREAD

**Issue by jpallas** [twosigma/beakerx#5544]
The current stable Spark release (2.1) is based on Scala 2.11 and incompatible with Scala 2.12, and the upcoming 2.2 release is also not supporting Scala 2.12 (see [mail thread](http://apache-spark-developers-list.1001551.n3.nabble.com/RFC-removing-Scala-2-10-tp21116p21124.html)).

Of course, Scala 2.12 has other benefits, including better integration and performance with Java 8.  And unless/until the Spark/Scala integration of classic Beaker can be ported to the BeakerX Scala kernel, maybe it's not that important.

**Comment by scottdraves** [comment]
thx good point

**Comment by konstantinTarletski** [comment]
I tried to switch to version 2.11.11. But get some Scala compilation errors.
```
:kernel:scala:compileScala
C:\WorkspaceBeakerx\beakerx\kernel\scala\src\main\java\com\twosigma\beakerx\scala\fileloader\CsvPlotReader.scala:25: not found: value asScalaBuffer
    val refactoredOutput : List[util.Map[_,_]] = asScalaBuffer(javaOutput).toList
                                                 ^
C:\WorkspaceBeakerx\beakerx\kernel\scala\src\main\java\com\twosigma\beakerx\scala\fileloader\CsvPlotReader.scala:27: not found: value mapAsScalaMap
    refactoredOutput.map(ro => mapAsScalaMap(ro).toMap)
                               ^
C:\WorkspaceBeakerx\beakerx\kernel\scala\src\main\java\com\twosigma\beakerx\scala\table\TableDisplay.scala:31: not found: value mapAsJavaMap
    new com.twosigma.beakerx.table.TableDisplay(mapAsJavaMap(v))
                                                ^
C:\WorkspaceBeakerx\beakerx\kernel\scala\src\main\java\com\twosigma\beakerx\scala\table\TableDisplay.scala:42: not found: value mapAsJavaMap
    val javaStandardized : Array[java.util.Map[_, _]]= v.map(v => mapAsJavaMap(v)).toArray
                                                                  ^
C:\WorkspaceBeakerx\beakerx\kernel\scala\src\main\java\com\twosigma\beakerx\scala\table\TableDisplay.scala:42: value toArray is not a member of Array[Nothing]
    val javaStandardized : Array[java.util.Map[_, _]]= v.map(v => mapAsJavaMap(v)).toArray
                                                                                   ^
C:\WorkspaceBeakerx\beakerx\kernel\scala\src\main\java\com\twosigma\beakerx\scala\table\TableDisplay.scala:48: not found: value mapAsJavaMap
    val javaMaps : List[java.util.Map[_,_]] = v.map(entry => mapAsJavaMap(entry))
                                                             ^
C:\WorkspaceBeakerx\beakerx\kernel\scala\src\main\java\com\twosigma\beakerx\scala\table\TableDisplay.scala:55: not found: value mapAsJavaMap
    val javaMaps : List[java.util.Map[_,_]] = v.map(entry => mapAsJavaMap(entry))
                                                             ^
C:\WorkspaceBeakerx\beakerx\kernel\scala\src\main\scala\com\twosigma\beaker\scala\evaluator\ScalaEvaluatorGlue.scala:47: value complete is not a member of scala.tools.nsc.interpreter.Completion
      val Candidates(newCursor, newCandidates) = completion.complete(buf, cursor)
                                                            ^
C:\WorkspaceBeakerx\beakerx\kernel\scala\src\main\scala\com\twosigma\beaker\scala\evaluator\ScalaEvaluatorGlue.scala:45: type mismatch;
 found   : (String, Int, tools.nsc.interpreter.JList[CharSequence]) => Int
    (which expands to)  (String, Int, java.util.List[CharSequence]) => Int
 required: scala.tools.jline_embedded.console.completer.Completer
    (_buf: String, cursor: Int, candidates: JList[CharSequence]) => {
                                                                 ^
9 errors found
:kernel:scala:compileScala FAILED
```
After that I asked for help from Michal. And get this answer :
```
to downgrade to version 2.11
we have to propobly rewrite Scala API for our libraries
it’s a lot of work
```

**Comment by michalgce** [comment]
Downgrading Scala 2.12 to 2.11 will be expensive cause we're using from function which was provided in 2.12 like converting lambda expressions to types with a "single abstract method" (SAM), aka "Functional Interface", like Java 8.

**Comment by scottdraves** [comment]
Unfortunate but Spark integration is critical.

**Comment by jpallas** [comment]
It looks like the names of some of the explicit conversions changed between 2.11 and 2.12.  I think the conversions should work in 2.11 using `.asJava`/`.asScala` implicits instead of ones like `mapAsJavaMap`.  (But I haven't actually tried it.)
